---
- hosts: all
  gather_facts: no
  become: yes
  name: enable package forwarding
  tasks:
    - name: enable package forwarding
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes