---
- hosts: master
  become: true
  tasks:
  - name: Extract file
    ansible.builtin.fetch:
      src: /etc/kubernetes/admin.conf
      dest: ~/.kube/config
      flat: yes

  - name: Create .kube directory
    ansible.builtin.file:
      path: "{{ ansible_env.HOME }}/.kube"
      state: directory
      mode: '0755'

  - name: Copy admin.conf to remote user's home directory
    ansible.builtin.copy:
      src: /etc/kubernetes/admin.conf
      dest: "{{ ansible_env.HOME }}/.kube/config"
      remote_src: yes
