---
- hosts: all
  become: yes
  gather_facts: no
  name: Install Docker
  tasks:
    - name: Add Jenkins key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
    - name: Add Jenkins repository to apt
      ansible.builtin.apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
    - name: Install fontconfig package
      ansible.builtin.apt:
        name:
          - fontconfig
    - name: Install openjdk-17-jre package
      ansible.builtin.apt:
        name:
          - openjdk-17-jre
    - name: Install Jenkins
      ansible.builtin.apt:
        name:
          - jenkins
