---
- hosts: all
  gather_facts: no
  become: yes
  name: Install k8s
  tasks:
    - name: Add Kubernetes GPG key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - name: Add Kubernetes repository to apt
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /
    - name: Install k8s package
      ansible.builtin.apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present