---
- hosts: all
  gather_facts: no
  become: yes
  name: Install Containerd
  tasks:
    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
    - name: Add Docker repository to apt
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable
    - name: Install containerd
      ansible.builtin.apt:
        name:
          - containerd.io
    - name: Create containerd config file
      ansible.builtin.command:
        cmd: containerd config default | tee /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml
    - name: Enable SystemdCgroup using simplified sed
      ansible.builtin.shell: sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
