---
- name: Install Flannel CNI plugin
  hosts: master
  become: yes
  tasks:
    - name: Apply Flannel manifest using kubectl
      ansible.builtin.command: >
        kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: flannel_output
    - name: Print Flannel installation output
      debug:
        var: flannel_output.stdout_lines
