
---
- hosts: master
  gather_facts: yes
  become: no
  name: Initialize Kubernetes Cluster
  tasks:
    # - name: Initialize using kubeadm
    #   ansible.builtin.command: kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket unix:///run/containerd/containerd.sock --apiserver-advertise-address={{ ansible_default_ipv4.address }}
    - name: Copy kube config to user directory
      ansible.builtin.command: sudo cp /etc/kubernetes/admin.conf /home/{{ ansible_user_id }}/.kube/config
    - name: Install Flannel CNI
      ansible.builtin.command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    
  
