---
- hosts: all
  gather_facts: no
  become: yes
  name: Setup k8s pre requisites
  tasks:
    - name: enable package forwarding
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes
    - name: Enable br_netfilter
      ansible.builtin.modprobe:
        name: br_netfilter
        state: present
        persistent: present # Load the module at boot time
    - name: Enable overlay
      ansible.builtin.modprobe:
        name: overlay
        state: present
        persistent: present # Load the module at boot time
    - name: Enable iptables
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: yes
    - name: Enable ip6tables
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present
        reload: yes
    - name: Enable iptables for IPv4
      ansible.builtin.sysctl:
        name: net.ipv4.conf.all.forwarding
        value: 1
        state: present
        reload: yes
    - name: Enable iptables for IPv6
      ansible.builtin.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: 1
        state: present
        reload: yes